Repository goormthon-Univ/2024_BEOTKKOTTHON_TEAM_20_BE, pull requests merged in 2024-03, with the labels that each got.

#4 [~3/15] 게시글 기능 제작
  .gitignore
  src/main/java/com/beotkkot/qtudy/common/ResponseCode.java
  src/main/java/com/beotkkot/qtudy/common/ResponseMessage.java
  src/main/java/com/beotkkot/qtudy/controller/post/PostApiController.java
  src/main/java/com/beotkkot/qtudy/domain/category/Category.java
  src/main/java/com/beotkkot/qtudy/domain/comments/Comments.java
  src/main/java/com/beotkkot/qtudy/domain/posts/Posts.java
  src/main/java/com/beotkkot/qtudy/domain/primaryKey/ScrapPk.java
  src/main/java/com/beotkkot/qtudy/domain/scrap/Scrap.java
  src/main/java/com/beotkkot/qtudy/domain/tags/Tags.java
  src/main/java/com/beotkkot/qtudy/dto/object/PostListItem.java
  src/main/java/com/beotkkot/qtudy/dto/request/posts/PostsRequestDto.java
  src/main/java/com/beotkkot/qtudy/dto/response/ResponseDto.java
  src/main/java/com/beotkkot/qtudy/dto/response/posts/GetPostsAllResponseDto.java
  src/main/java/com/beotkkot/qtudy/dto/response/posts/GetPostsResponseDto.java
  src/main/java/com/beotkkot/qtudy/dto/response/posts/PostsResponseDto.java
  src/main/java/com/beotkkot/qtudy/dto/response/posts/PutScrapResponseDto.java
  src/main/java/com/beotkkot/qtudy/repository/comments/CommentsRepository.java
  src/main/java/com/beotkkot/qtudy/repository/posts/PostsRepository.java
  src/main/java/com/beotkkot/qtudy/repository/scrap/ScrapRepository.java
  src/main/java/com/beotkkot/qtudy/repository/tags/TagsRepository.java
  src/main/java/com/beotkkot/qtudy/service/posts/PostsService.java
Labels: feature

#8 [Feat] 요약 기능 구현
  src/main/java/com/beotkkot/qtudy/controller/auth/AuthController.java
  src/main/java/com/beotkkot/qtudy/controller/post/SummarizationController.java
  src/main/java/com/beotkkot/qtudy/dto/request/posts/PostsRequestDto.java
  src/main/java/com/beotkkot/qtudy/dto/response/posts/GetSummaryResponseDto.java
  src/main/java/com/beotkkot/qtudy/service/posts/PostsService.java
  src/main/java/com/beotkkot/qtudy/service/posts/SummaryService.java
Labels: feature

#21 [Feat] 댓글 기능 구현
  src/main/java/com/beotkkot/qtudy/controller/comment/CommentController.java
  src/main/java/com/beotkkot/qtudy/domain/comments/Comments.java
  src/main/java/com/beotkkot/qtudy/dto/object/CommentListItem.java
  src/main/java/com/beotkkot/qtudy/dto/request/comments/CommentsRequestDto.java
  src/main/java/com/beotkkot/qtudy/dto/response/comments/CommentsResponseDto.java
  src/main/java/com/beotkkot/qtudy/dto/response/comments/GetCommentsAllResponseDto.java
  src/main/java/com/beotkkot/qtudy/repository/comments/CommentsRepository.java
  src/main/java/com/beotkkot/qtudy/service/comments/CommentService.java
  src/main/java/com/beotkkot/qtudy/service/posts/PostsService.java
Labels: feature

#26 [Feat] Add `findTagsByCategoryId`
  src/main/java/com/beotkkot/qtudy/controller/tag/TagApiController.java
  src/main/java/com/beotkkot/qtudy/repository/tags/TagsRepository.java
  src/main/java/com/beotkkot/qtudy/service/tag/TagService.java
Labels: feature

#25 [Refactor] refactoring
  src/main/java/com/beotkkot/qtudy/config/WebConfig.java
  src/main/java/com/beotkkot/qtudy/domain/tags/Tags.java
  src/main/java/com/beotkkot/qtudy/dto/object/PostListItem.java
  src/main/java/com/beotkkot/qtudy/dto/response/posts/GetPostsAllResponseDto.java
  src/main/java/com/beotkkot/qtudy/dto/response/tags/GetTagsResponseDto.java
  src/main/java/com/beotkkot/qtudy/repository/posts/PostsRepository.java
  src/main/java/com/beotkkot/qtudy/repository/scrap/ScrapRepository.java
  src/main/java/com/beotkkot/qtudy/service/posts/PostsService.java
Labels: refactor

#29 [Feat] 내가 푼 문제(review) 기능 추가
  src/main/java/com/beotkkot/qtudy/controller/quiz/QuizController.java
  src/main/java/com/beotkkot/qtudy/domain/quiz/Review.java
  src/main/java/com/beotkkot/qtudy/dto/object/ReviewDetailListItem.java
  src/main/java/com/beotkkot/qtudy/dto/object/ReviewListItem.java
  src/main/java/com/beotkkot/qtudy/dto/request/quiz/GradeQuizRequestDto.java
  src/main/java/com/beotkkot/qtudy/dto/response/posts/PostsResponseDto.java
  src/main/java/com/beotkkot/qtudy/dto/response/quiz/GetPostQuizResponseDto.java
  src/main/java/com/beotkkot/qtudy/dto/response/quiz/GetReviewResponseDto.java
  src/main/java/com/beotkkot/qtudy/dto/response/quiz/ReviewResponseDto.java
  src/main/java/com/beotkkot/qtudy/repository/quiz/QuizRepository.java
  src/main/java/com/beotkkot/qtudy/repository/quiz/ReviewRepository.java
  src/main/java/com/beotkkot/qtudy/service/posts/PostsService.java
  src/main/java/com/beotkkot/qtudy/service/quiz/QuizService.java
  src/main/java/com/beotkkot/qtudy/service/quiz/ReviewService.java
  src/main/resources/application.yml
Labels: feature

#33 [FIX] Transactional BUG
  src/main/java/com/beotkkot/qtudy/service/posts/PostsService.java
  src/main/java/com/beotkkot/qtudy/service/posts/SummaryService.java
  src/main/resources/application.yml
Labels: bug, refactor

#37 kakao oauth refactoring
  src/main/java/com/beotkkot/qtudy/service/auth/AuthService.java
  src/main/resources/application.yml
Labels: refactor

#40 [Refactor] 포스트 수정 시 글 재요약
  src/main/java/com/beotkkot/qtudy/service/posts/PostsService.java
Labels: refactor

#41 [Refactor] 댓글 전체 조회 -> 사용자 이름, 프로필 이미지 추가
  src/main/java/com/beotkkot/qtudy/dto/object/CommentListItem.java
  src/main/java/com/beotkkot/qtudy/service/comments/CommentService.java
Labels: refactor

#44 [Feat] Add `GetPostsScrap`
  src/main/java/com/beotkkot/qtudy/controller/post/PostApiController.java
  src/main/java/com/beotkkot/qtudy/repository/posts/PostsRepository.java
  src/main/java/com/beotkkot/qtudy/service/posts/PostsService.java
Labels: feature

#47 [Feat] 스크랩 최신 날짜 기준으로 정렬하기
  src/main/java/com/beotkkot/qtudy/domain/scrap/Scrap.java
  src/main/java/com/beotkkot/qtudy/repository/posts/PostsRepository.java
  src/main/java/com/beotkkot/qtudy/service/posts/PostsService.java
Labels: feature

#50 Modify gpt-model
  src/main/java/com/beotkkot/qtudy/service/quiz/QuizService.java
Labels: refactor

#53 [HOT FIX] getMyReviewList bug fix
  src/main/java/com/beotkkot/qtudy/repository/quiz/QuizRepository.java
  src/main/java/com/beotkkot/qtudy/repository/quiz/ReviewRepository.java
  src/main/java/com/beotkkot/qtudy/service/posts/PostsService.java
Labels: bug

#57 [Refactor] 엔티티 Setter 제거
  src/main/java/com/beotkkot/qtudy/domain/category/Category.java
  src/main/java/com/beotkkot/qtudy/domain/comments/Comments.java
  src/main/java/com/beotkkot/qtudy/domain/interests/Interests.java
  src/main/java/com/beotkkot/qtudy/domain/posts/Posts.java
  src/main/java/com/beotkkot/qtudy/domain/primaryKey/InterestsPK.java
  src/main/java/com/beotkkot/qtudy/domain/primaryKey/ScrapPk.java
  src/main/java/com/beotkkot/qtudy/domain/quiz/Quiz.java
  src/main/java/com/beotkkot/qtudy/domain/quiz/Review.java
  src/main/java/com/beotkkot/qtudy/domain/tags/Tags.java
  src/main/java/com/beotkkot/qtudy/domain/user/Users.java
  src/main/java/com/beotkkot/qtudy/dto/request/comments/CommentsRequestDto.java
  src/main/java/com/beotkkot/qtudy/service/auth/AuthService.java
  src/main/java/com/beotkkot/qtudy/service/posts/PostsService.java
  src/main/java/com/beotkkot/qtudy/service/quiz/QuizService.java
  src/main/java/com/beotkkot/qtudy/service/user/UserService.java
Labels: refactor
